// Mocks generated by Mockito 5.4.2 from annotations
// in weekly/test/unit_test/features/home/view-model/articles_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:weekly/features/home/model/articles.dart' as _i7;
import 'package:weekly/features/home/repository/article_repository.dart' as _i4;
import 'package:weekly/product/utils/network_manager.dart' as _i2;
import 'package:weekly/product/utils/server_exception.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkManager_0 extends _i1.SmartFake
    implements _i2.NetworkManager {
  _FakeNetworkManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRepository extends _i1.Mock implements _i4.ArticleRepository {
  MockArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NetworkManager get networkManager => (super.noSuchMethod(
        Invocation.getter(#networkManager),
        returnValue: _FakeNetworkManager_0(
          this,
          Invocation.getter(#networkManager),
        ),
      ) as _i2.NetworkManager);
  @override
  _i5.Future<_i3.Either<_i6.ServerException, _i7.Articles>>
      fetchPopularArticles() => (super.noSuchMethod(
            Invocation.method(
              #fetchPopularArticles,
              [],
            ),
            returnValue:
                _i5.Future<_i3.Either<_i6.ServerException, _i7.Articles>>.value(
                    _FakeEither_1<_i6.ServerException, _i7.Articles>(
              this,
              Invocation.method(
                #fetchPopularArticles,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i6.ServerException, _i7.Articles>>);
}
